[Settings]
  ID = "2cc39115-aff6-4bd5-a32e-00e1e73c6343"

[build]
  base    = "UI/"
  publish = "UI/dist/"
  command = "npm run rebuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
