//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onboarding.Resources.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentValidations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentValidations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("onboarding.Resources.Enums.DocumentValidations", typeof(DocumentValidations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNE.
        /// </summary>
        public static string Foreigner {
            get {
                return ResourceManager.GetString("Foreigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parecer da secretaria de educação e publicação no diário oficial.
        /// </summary>
        public static string ForeignGraduation {
            get {
                return ResourceManager.GetString("ForeignGraduation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaração de conclusão do ensino médio ou histórico escolar.
        /// </summary>
        public static string GraduationYear {
            get {
                return ResourceManager.GetString("GraduationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Militar.
        /// </summary>
        public static string MilitaryDraft {
            get {
                return ResourceManager.GetString("MilitaryDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título de Eleitor e Comprovante de Votação.
        /// </summary>
        public static string MinorAge {
            get {
                return ResourceManager.GetString("MinorAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string Native {
            get {
                return ResourceManager.GetString("Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico escolar.
        /// </summary>
        public static string NotGraduationYear {
            get {
                return ResourceManager.GetString("NotGraduationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certidão de casamento obrigatória.
        /// </summary>
        public static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
    }
}
